fix front end compile error (#76)
Problem
GitHub workflow failed with the following error:

```
```

Solution
- Was able to reproduce the error locally by using `yarn build` instead
of `yarn lint`. It is a compilation error but due to output seems
like a linting error.

Ticket URL
N/A

Documentation
N/A

Tests Run
- Test locally by running `yarn build` instead of `yarn lint`
- Checked functionality of the app locally